  export const carColorItems = [
  { label: "White", value: "White" },
  { label: "Black", value: "Black" },
  { label: "Gray", value: "Gray" },
  { label: "Silver", value: "Silver" },
  { label: "Blue", value: "Blue" },
  { label: "Red", value: "Red" },
  { label: "Brown", value: "Brown" },
  { label: "Green", value: "Green" },
  { label: "Beige / Tan", value: "Beige" },  
  { label: "Gold", value: "Gold" },
  { label: "Yellow", value: "Yellow" },
  { label: "Orange", value: "Orange" },
  { label: "Purple", value: "Purple" },
  { label: "Burgundy / Maroon", value: "Burgundy" },
  { label: "Teal / Aqua", value: "Teal" },
  { label: "Light Blue", value: "Light Blue" },
  { label: "Matte Black", value: "Matte Black" },
  { label: "Matte Gray", value: "Matte Gray" },
  { label: "Two-Tone", value: "Two-Tone" },
  { label: "Primer Gray", value: "Primer Gray" },
];
